### ISSUE TITLE
Building sambamba

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/guix-bioinformatics#3]
@roelj In https://github.com/genenetwork/guix-bioinformatics/commit/2933faad1298777e76584fff3b6fc0bcaa6c50b1 I have updated the sambamba variable to build against my git checkout which contains a working 

  make -f Makefile.guix

The current version builds with an `ERROR: In procedure mkstemp!: Permission denied' because the target directory is immutable. Please use the procedure in https://github.com/genenetwork/guix/blob/gn-stable/gnu/packages/ldc.scm to fetch BioD and copy it locally and build after.

**Comment by roelj** [comment]
With the latest version, this should be fixed. Thanks a lot for the Makefile.guix.

**Comment by roelj** [comment]
We now don't need the custom Makefile.guix anymore. There's still that crash left..

**Comment by pjotrp** [comment]
Sambamba works on Guix.
