### ISSUE TITLE
Write cuOmicABLE package

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/guix-bioinformatics#4]
@Brainiarc7 https://github.com/Brainiarc7 We would like to try the CUDA version of OmicABLE. Build it first without CUDA and then with. If it works and is not too buggy it may make it into GeneNetwork.

**Comment by Brainiarc7** [comment]
Taken to task.

**Comment by pjotrp** [comment]
Removing this. cuOmicABLE is not worth the trouble.
